In [4]:
import numpy as np
a = np.arange(6)
print(a)
a = a.reshape((3, 2))
print(a)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [6]:
a = np.arange(6)
np.reshape(a, (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
a = np.array([[1,2,3], [4,5,6]])

In [8]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [17]:
np.reshape(a, (6,-1), order='F')

array([[1],
       [4],
       [2],
       [5],
       [3],
       [6]])

In [18]:
len(np.array([[1,2],[3,4],[5,6]]))
len(np.array([[2,3,1,0], [2,3,1,0], [3,2,1,1]]).T)

4

In [19]:
x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x)

6917529010461212688

In [20]:
np.prod([])

1.0

In [21]:
np.prod([1,2])

2

In [22]:
np.prod([[1,2],[3,4]])

24

In [25]:
np.prod([[1,2],[3,4]], axis = 0)

array([3, 8])